[masters]
node-1 ansible_host=192.168.56.11 v_name=wacloud-node-1

[workers]
node-2 ansible_host=192.168.56.12 v_name=wacloud-node-2
node-3 ansible_host=192.168.56.13 v_name=wacloud-node-3
node-4 ansible_host=192.168.56.14 v_name=wacloud-node-4

[all:vars]
ansible_user=vagrant
ansible_become=yes
# THE CORRECTED PATH based on your tree:
ansible_ssh_private_key_file="{{ lookup('env', 'PWD') }}/infra/vm/vagrant/.vagrant/machines/{{ v_name }}/virtualbox/private_key"
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o PubkeyAcceptedAlgorithms=+ssh-rsa'

ansible_python_interpreter=/usr/bin/python3
