---
- name: Check available disks (Debug info)
  shell: lsblk -dn -o NAME,SIZE | grep -v sda
  register: available_disks
  changed_when: false

- name: Find the OSD disk (Any disk that is NOT sda and > 2GB)
  shell: |
    lsblk -dnbo NAME,SIZE,TYPE | \
    awk '$3=="disk" && $1!="sda" && $2>2147483648 {print "/dev/"$1}' | head -n1
  register: found_osd_disk
  changed_when: false

- name: Wipe the OSD disk signatures
  shell: |
    wipefs -a {{ found_osd_disk.stdout }}
    dd if=/dev/zero of={{ found_osd_disk.stdout }} bs=1M count=20 conv=notrunc
  when: found_osd_disk.stdout != ""
  ignore_errors: yes

- name: Add OSDs for all nodes
  shell: ceph orch daemon add osd {{ item }}:{{ hostvars[item].found_osd_disk.stdout }}
  loop: "{{ groups['ceph_osds'] }}"
  when:
    - inventory_hostname == groups['ceph_mons'][0]
    - hostvars[item].found_osd_disk.stdout is defined
    - hostvars[item].found_osd_disk.stdout != ""
  ignore_errors: yes

- name: Wait for OSDs to be up
  shell: "ceph osd stat | grep -E '{{ groups['ceph_osds'] | length }} osds'"
  register: osd_stat
  until: osd_stat.rc == 0
  retries: 20
  delay: 15
  when: inventory_hostname == groups['ceph_mons'][0]

- name: Create RBD pool for KubeVirt
  shell: |
    if ! ceph osd pool ls | grep -w rbd; then
      ceph osd pool create rbd 32
      ceph osd pool application enable rbd rbd
      rbd pool init rbd
    fi
  when: inventory_hostname == groups['ceph_mons'][0]

- name: Deploy RGW
  shell: ceph orch apply rgw myrgw --placement="{{ groups['ceph_mons'][0] }}"
  when: inventory_hostname == groups['ceph_mons'][0]
  ignore_errors: yes
