---
- name: Reload systemd and restart kubelet with correct node-ip BEFORE init
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
  ignore_errors: yes

- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kube_init_done

- name: Initialize Kubernetes Cluster
  shell: |
    kubeadm init \
    --apiserver-advertise-address=192.168.56.11 \
    --pod-network-cidr=10.244.0.0/16 \
    --node-name {{ inventory_hostname }} \
    --cri-socket unix:///var/run/containerd/containerd.sock \
    --ignore-preflight-errors=all
  when: not kube_init_done.stat.exists
  register: init_output

- name: Create .kube directory for vagrant user
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant

- name: Wait for API Server to be healthy
  uri:
    url: https://192.168.56.11:6443/healthz
    validate_certs: no
  register: api_health
  until: api_health.status == 200
  retries: 20
  delay: 10

- name: Install Flannel Network Plugin
  become_user: vagrant
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml --validate=false
  register: flannel_result
  until: flannel_result.rc == 0
  retries: 5
  delay: 10

- name: Get Join Command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command as a fact
  set_fact:
    join_command: "{{ join_command_raw.stdout }} --cri-socket unix:///var/run/containerd/containerd.sock"
