[ceph_mons]
wacloud-node-6 ansible_host=192.168.56.16 v_name=wacloud-node-6
wacloud-node-7 ansible_host=192.168.56.17 v_name=wacloud-node-7
wacloud-node-8 ansible_host=192.168.56.18 v_name=wacloud-node-8

[ceph_osds]
wacloud-node-6 ansible_host=192.168.56.16 v_name=wacloud-node-6
wacloud-node-7 ansible_host=192.168.56.17 v_name=wacloud-node-7
wacloud-node-8 ansible_host=192.168.56.18 v_name=wacloud-node-8

[ceph_mgrs]
wacloud-node-6 ansible_host=192.168.56.16 v_name=wacloud-node-6

[all:vars]
ansible_user=vagrant
ansible_become=yes
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o PubkeyAcceptedAlgorithms=+ssh-rsa'
ansible_python_interpreter=/usr/bin/python3
