---
- name: Load bridge netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Persist bridge module on reboot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter

- name: Set bridge-nf-call-iptables to 1
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: Disable SWAP (K8s requirement)
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Install Prerequisite Packages
  apt:
    name: [apt-transport-https, ca-certificates, curl, software-properties-common, gnupg2]
    update_cache: yes

- name: Add Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Set Docker to use systemd cgroup driver
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Add Kubernetes GPG Key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: yes

- name: Add Kubernetes Repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    update_cache: yes

- name: Install K8s Tools
  apt:
    name: [kubelet, kubeadm, kubectl]
    state: present
    update_cache: yes
