Vagrant.configure("2") do |config|
  (1..8).each do |i|
    config.vm.define "wacloud-node-#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      node.disksize.size = "40GB"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "wacloud-node-#{i}"
        vb.cpus = 8
        if i <= 5
          vb.memory = 16384 
        else
          vb.memory = 8192
        end

        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end

      # Provisioning for Ansible
      node.vm.provision "shell", inline: <<-SHELL
        echo "vagrant:vagrant" | sudo chpasswd
      SHELL
    end
  end
end
