Vagrant.configure("2") do |config|
  (1..4).each do |i|
    config.vm.define "wacloud-node-#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      node.disksize.size = "40GB"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "wacloud-node-#{i}"
        vb.memory = 16384 # 16GB RAM
        vb.cpus = 12      # 12 CPUs
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end

      # Automatically resize the partition inside the VM on boot
      # 1. Resize the partition inside the VM
      # 2. Ensure the 'vagrant' user has a known password for Ansible initial connection
      node.vm.provision "shell", inline: <<-SHELL
        echo "vagrant:vagrant" | sudo chpasswd
      SHELL
    end
  end
end
